Update CI (#6)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,22 +19,81 @@ jobs:
         os: [ubuntu-latest, macos-latest]
         include:
           - os: macos-latest
-            install_deps: brew install chezmoi
+            install_deps: |
+              brew install zsh chezmoi zoxide poetry
           - os: ubuntu-latest
-            install_deps: sudo apt-get update && sudo apt install zsh -y && sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin && export PATH="${HOME}/.local/bin:$PATH"
+            install_deps: |
+              sudo apt-get update
+              sudo apt install -y \
+                git \
+                zsh \
+                curl \
+                zoxide \
+                python3-poetry \
+                make \
+                wget \
+                llvm \
+                build-essential \
+                libbz2-dev \
+                libreadline-dev \
+                liblzma-dev \
+                libsqlite3-dev \
+                libssl-dev \
+                zlib1g-dev \
+                libncurses5-dev \
+                libncursesw5-dev \
+                libgdbm-dev \
+                libnss3-dev \
+                xz-utils \
+                tk-dev \
+                libffi-dev \
+                uuid-dev
+              sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin
+              export PATH="${HOME}/.local/bin:$PATH"
     steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          repository: marchdf/dotfiles
+          path: dotfiles
       - name: Dependencies
         run: |
           ${{matrix.install_deps}}
+      - name: Clone dotfiles
+        run: |
+          mkdir -p "$HOME/.local/share/chezmoi"
+          git config --global --add safe.directory "$HOME/.local/share/chezmoi"
+          git clone --depth 1 --branch "${{ github.head_ref || github.ref_name }}" https://github.com/marchdf/dotfiles.git "$HOME/.local/share/chezmoi"
       - name: Install
         run: |
-          export CHEZMOI_BRANCH=${{ github.head_ref || github.ref_name }}
-          chezmoi init https://github.com/marchdf/dotfiles.git --branch ${CHEZMOI_BRANCH} --promptBool test_machine=t,"Use ZSH_ROOT_DIR for tmux shell"=f --promptString email=""
+          chezmoi init --source="$HOME/.local/share/chezmoi" --promptBool test_machine=t,"Use ZSH_ROOT_DIR for tmux shell"=f --promptString email=""
           chezmoi data
           chezmoi apply
       - name: Cold start zsh
+        env:
+          TERM: xterm-256color
         run: |
           time zsh -i -c exit
       - name: Warm start zsh
+        env:
+          TERM: xterm-256color
         run: |
           time zsh -i -c exit
+      - name: Verify tools
+        env:
+          TERM: xterm-256color
+          DISABLE_AUTO_TITLE: true
+        shell: zsh {0}
+        run: |
+          if [[ "$RUNNER_OS" == "Linux" ]]; then
+            export PATH="/home/runner/.fzf/bin:$PATH"
+          fi
+          source ~/.zshrc
+          for TOOL in python pyenv poetry zoxide fzf bat; do
+            if ! command -v "${TOOL}" >/dev/null; then
+              echo "${TOOL} not found!"
+              exit 1
+            else
+              echo "${TOOL} found: $(${TOOL} --version 2>&1 | head -n1)"
+            fi
+          done
